### ISSUE TITLE
Small issue with  gnome shell version 44 

### ISSUE THREAD

**Issue by dasnoopy** [linushdot/unsafe-mode-menu#3]
Hi, 

even if "not officially supported" ,  I tried to install the extension  in gnome 44  as per   `README.md `instructions;
then I  modified the `metadata.json` file adding gnome 44 version

The extensions seem works pretty well but no text is displayed near the icon on quick setting button:

![Screenshot from 2023-06-22 06-48-07](https://github.com/linushdot/unsafe-mode-menu/assets/296922/e505721d-7e7a-41b8-8204-b411140be296)

Any chance to add support for gnome 44?

Thanks in advance
Andrea

Gnome 44.2 on wayland (Archlinux)

**Comment by linushdot** [comment]
Thanks for raising the issue.

There was a small change in Gnome Shell, fixed it here: a7668cf6eeb31b6c6a12556ec100017f2abee749. The extension now also supports Gnome Shell 44.
