### ISSUE TITLE
Is there any way to toggle unsafe mode via terminal??

### ISSUE THREAD

**Issue by iitzrohan** [linushdot/unsafe-mode-menu#7]

**Comment by linushdot** [comment]
I assume you are looking for a way to toggle unsafe mode via terminal *using this extension*?

If you need it, I could add a setting to this extension which directly enables/disables the unsafe mode. This could then be changed via terminal. Would this help?

**Comment by linushdot** [comment]
New release v7: https://github.com/linushdot/unsafe-mode-menu/releases/tag/v7

This now allows to read and change unsafe mode using `dconf`:
```
dconf read /org/gnome/shell/extensions/unsafe-mode-menu/state
dconf write /org/gnome/shell/extensions/unsafe-mode-menu/state <true|false>
```

**Comment by iitzrohan** [comment]
Thanks for implementing it. It works now.
